### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [berbus/proyectoIV#7]
Hello @berbus 

In my free time I design logos to contribute to open source software. I designed a logo for the software function for your Repo. If you like it, i will send a all files via pr.

Please tell me what you think about it. I will wait for feedback. 
Have a nice day.

![proyecto](https://user-images.githubusercontent.com/36298335/46571859-f5dfbd80-c9d8-11e8-977a-11c60e1cc893.jpg)

**Comment by berbus** [comment]
Could you please change the name to aleatoriedapp. The logo looks cool like that ;)

**Comment by reallinfo** [comment]
of course, as you wish. is it like this?

![al](https://user-images.githubusercontent.com/36298335/46582465-c47ff400-caa3-11e8-8a1c-343cc8a62282.jpg)

**Comment by berbus** [comment]
Yeah! That looks awesome, thank you so much!

**Comment by reallinfo** [comment]
Oh, okay. I'll send you all the files very soon.

**Comment by reallinfo** [comment]
Sorry, I've created a few more variations while making the final edits. Please tell me which one you want. Also, I can send them all if you like. It doesn't matter to me. All files are ready. I'll send a pr when you decide.

![al](https://user-images.githubusercontent.com/36298335/46585753-48040a00-cad1-11e8-8117-5c7754498906.jpg)

**Comment by berbus** [comment]
That looks perfect. Please, send them all so I can try them and see which one looks better. I still haven't decided the web layout :P

**Comment by reallinfo** [comment]
Thank you. I sent a pr. I am sorry for the delay. I have placed svg and png formats of all variations. Also, i updated the readme file. you can still add any variation to the readme file. If there are any problems please contact me.
